// GENERATED from MaxPreps 26-27 varsity rosters. Real teams for the
// Columbia City @ Northridge game. Two-way athletes: primary (first-listed)
// position is used as the label.

export const NORTHRIDGE_ROSTER = [
  { n: 1, name: "Thomas Nusbaum", pos: "TE" },
  { n: 2, name: "Payton Konecny", pos: "WR" },
  { n: 3, name: "Keivontre Copeland", pos: "WR" },
  { n: 4, name: "Tate Granberg", pos: "OL" },
  { n: 5, name: "Adam Sloop", pos: "RB" },
  { n: 6, name: "Aaron King", pos: "LB" },
  { n: 7, name: "Hayden Gorball", pos: "WR" },
  { n: 8, name: "Jack Smith", pos: "RB" },
  { n: 9, name: "Eli Stec", pos: "K" },
  { n: 10, name: "Carson Duncan", pos: "LB" },
  { n: 11, name: "Myhles Norman", pos: "CB" },
  { n: 12, name: "Karsyn Rumfelt", pos: "QB" },
  { n: 13, name: "Jaxton Miller", pos: "WR" },
  { n: 14, name: "Micah Beiler", pos: "S" },
  { n: 16, name: "Jake Scholl", pos: "QB" },
  { n: 17, name: "Maxwell Lamb", pos: "DL" },
  { n: 19, name: "Jackson Estep", pos: "DL" },
  { n: 22, name: "Cisco Guerrero", pos: "WR" },
  { n: 23, name: "Sam Titov", pos: "RB" },
  { n: 24, name: "Malachi Graber", pos: "WR" },
  { n: 25, name: "Sylas Richer", pos: "RB" },
  { n: 26, name: "Hudson Scott", pos: "TE" },
  { n: 29, name: "Brayden Lantz", pos: "S" },
  { n: 30, name: "Toby Miller", pos: "WR" },
  { n: 31, name: "Jediah Hochstetler", pos: "WR" },
  { n: 32, name: "Kane Yeater", pos: "RB" },
  { n: 33, name: "Cole Yeater", pos: "RB" },
  { n: 34, name: "Roman Jessup", pos: "WR" },
  { n: 39, name: "Kasen Hunter", pos: "RB" },
  { n: 40, name: "Tate Baber", pos: "WR" },
  { n: 41, name: "Timothy Willis", pos: "WR" },
  { n: 43, name: "Braedynn Rolston", pos: "LB" },
  { n: 44, name: "Liam Kaehr", pos: "TE" },
  { n: 45, name: "Colt Granberg", pos: "LB" },
  { n: 50, name: "Dylan Holmes", pos: "OL" },
  { n: 51, name: "Zac Zimmerman", pos: "OL" },
  { n: 53, name: "Leo Muller", pos: "DL" },
  { n: 54, name: "Chapman Brinks", pos: "DL" },
  { n: 55, name: "Eddie Klain", pos: "OL" },
  { n: 56, name: "A.J. Hildenbrand", pos: "OL" },
  { n: 57, name: "A.J. Diller", pos: "OL" },
  { n: 58, name: "Tyler Holmes", pos: "OL" },
  { n: 63, name: "Bryce Schrock", pos: "OL" },
  { n: 64, name: "Gavin Hilary", pos: "DL" },
  { n: 65, name: "Gabriel Zambrano", pos: "OL" },
  { n: 66, name: "Braxton Young", pos: "OL" },
  { n: 67, name: "Lucas Holland", pos: "OL" },
  { n: 71, name: "Santiago Guzman", pos: "OL" },
  { n: 73, name: "Mason Simmons", pos: "OL" },
  { n: 74, name: "Gabriel Miller", pos: "OL" },
  { n: 75, name: "Levi Byers", pos: "OL" },
  { n: 76, name: "Marc Swoape", pos: "OL" },
  { n: 78, name: "Cannon Ganger", pos: "OL" },
  { n: 79, name: "Breydon Gingerich", pos: "OL" },
  { n: 83, name: "Aiden Wogoman", pos: "WR" },
  { n: 84, name: "Jakson Holloway", pos: "WR" },
  { n: 87, name: "Augy Judd", pos: "WR" },
  { n: 88, name: "Jace Daniels", pos: "WR" },
];

export const COLUMBIA_CITY_ROSTER = [
  { n: 0, name: "Jaxson Johnson", pos: "K" },
  { n: 2, name: "Tannor Ellis", pos: "CB" },
  { n: 3, name: "Colton Schroeder", pos: "LB" },
  { n: 4, name: "Gabe McDevitt", pos: "WR" },
  { n: 5, name: "Liam Sheets", pos: "RB" },
  { n: 6, name: "Noah Geiger", pos: "RB" },
  { n: 7, name: "Jace Pettigrew", pos: "DL" },
  { n: 8, name: "Rj Getts", pos: "FB" },
  { n: 9, name: "Davon Suel", pos: "S" },
  { n: 10, name: "Jaiden Williams", pos: "QB" },
  { n: 11, name: "Riley Baxter", pos: "WR" },
  { n: 12, name: "Adam Edgell", pos: "WR" },
  { n: 13, name: "Ian Berry", pos: "WR" },
  { n: 15, name: "Chase Laliberte", pos: "QB" },
  { n: 16, name: "Reece Smith", pos: "QB" },
  { n: 17, name: "Jordan Parrett", pos: "QB" },
  { n: 18, name: "Dylan Faust", pos: "S" },
  { n: 19, name: "Deklin Cody", pos: "RB" },
  { n: 20, name: "Tucker Durand", pos: "CB" },
  { n: 21, name: "Sam Newman", pos: "WR" },
  { n: 22, name: "Grady Osselaer", pos: "RB" },
  { n: 24, name: "Lukas Duncan", pos: "WR" },
  { n: 25, name: "Trentin McClellan", pos: "WR" },
  { n: 27, name: "Lukas Sandkuhler", pos: "RB" },
  { n: 28, name: "Makzton Mathews", pos: "QB" },
  { n: 31, name: "Harris Wagner", pos: "CB" },
  { n: 32, name: "Corbin McIntosh", pos: "LB" },
  { n: 33, name: "Noah Gipe", pos: "FB" },
  { n: 34, name: "Jordan Hargrave", pos: "RB" },
  { n: 40, name: "Levi Baxter", pos: "TE" },
  { n: 41, name: "Nicholas Venable", pos: "WR" },
  { n: 42, name: "John Jordan", pos: "WR" },
  { n: 43, name: "Braxton Fuller", pos: "RB" },
  { n: 44, name: "Devin Meinika", pos: "FB" },
  { n: 45, name: "Trae Barnes", pos: "RB" },
  { n: 46, name: "Mathias Sleighter", pos: "WR" },
  { n: 50, name: "Austin Pieper", pos: "LB" },
  { n: 53, name: "Zachary Furthmiller", pos: "OL" },
  { n: 54, name: "Jake Slater", pos: "DL" },
  { n: 55, name: "Eli Pieper", pos: "QB" },
  { n: 57, name: "Jedrian Rosado", pos: "OL" },
  { n: 58, name: "Connor Cook", pos: "TE" },
  { n: 59, name: "Alden Ames", pos: "OL" },
  { n: 61, name: "Braden Leininger", pos: "OL" },
  { n: 62, name: "Jacob Anderson", pos: "OL" },
  { n: 63, name: "Jax Heller", pos: "OL" },
  { n: 65, name: "Sawyer Kauffman", pos: "OL" },
  { n: 67, name: "Alex Ravare", pos: "OL" },
  { n: 68, name: "Braxton Vaught", pos: "OL" },
  { n: 69, name: "Gavin Shepherd", pos: "DL" },
  { n: 70, name: "Dorian Bunn", pos: "OL" },
  { n: 72, name: "Caden Bohnstedt", pos: "OL" },
  { n: 73, name: "Logan Richmond", pos: "DL" },
  { n: 74, name: "Jon Furthmiller", pos: "OL" },
  { n: 75, name: "Tanner Rider", pos: "DL" },
  { n: 76, name: "Brayden Meinika", pos: "OL" },
  { n: 77, name: "Eathan Krider", pos: "OL" },
  { n: 78, name: "Braden Potts", pos: "OL" },
  { n: 80, name: "Graysen Moses", pos: "WR" },
  { n: 82, name: "Andrew Furthmiller", pos: "TE" },
  { n: 83, name: "Henry Summers", pos: "TE" },
  { n: 86, name: "Colin Howell", pos: "K" },
  { n: 87, name: "Alex Vasquez", pos: "WR" },
];

// Bellmont Braves (Decatur, IN) — 26-27 varsity, from MaxPreps (web, not a PDF).
// Positions simplified to the first-listed. Duplicate name spellings on the
// source page were de-duplicated by jersey number.
export const BELLMONT_ROSTER = [
  { n: 2, name: "Oliver Faurote", pos: "WR" },
  { n: 3, name: "Charlie Faurote", pos: "QB" },
  { n: 4, name: "Mason White", pos: "S" },
  { n: 5, name: "Cole Barger", pos: "WR" },
  { n: 6, name: "Corbynn Omlor", pos: "RB" },
  { n: 7, name: "Colin Ripley", pos: "CB" },
  { n: 9, name: "Corbin Summers", pos: "QB" },
  { n: 10, name: "George Curtis", pos: "S" },
  { n: 11, name: "Coltin Phillips", pos: "LB" },
  { n: 12, name: "Lawton Bultemeier", pos: "TE" },
  { n: 13, name: "Nate Buuck", pos: "CB" },
  { n: 15, name: "Ashton Lykins", pos: "RB" },
  { n: 16, name: "Eric Conrad", pos: "S" },
  { n: 18, name: "Konner Moser", pos: "QB" },
  { n: 20, name: "Henry Faurote", pos: "RB" },
  { n: 21, name: "Jacob David", pos: "S" },
  { n: 22, name: "Stanley Eaton", pos: "RB" },
  { n: 23, name: "Ethan Eicher", pos: "CB" },
  { n: 24, name: "Jackie Faust", pos: "WR" },
  { n: 27, name: "Bryar Skramstad", pos: "LB" },
  { n: 28, name: "Luke Summers", pos: "S" },
  { n: 29, name: "Zack Franze", pos: "WR" },
  { n: 32, name: "Callaway Conrad", pos: "RB" },
  { n: 35, name: "Ethan Mankey", pos: "LB" },
  { n: 36, name: "Kain Murphy", pos: "TE" },
  { n: 37, name: "Layne Sipe", pos: "S" },
  { n: 40, name: "Bentley Link", pos: "LB" },
  { n: 44, name: "Austin Manley", pos: "RB" },
  { n: 45, name: "Colten Cole", pos: "DL" },
  { n: 49, name: "Michael West", pos: "DL" },
  { n: 50, name: "Carter Ballard", pos: "OL" },
  { n: 51, name: "Cruz Becerra", pos: "OL" },
  { n: 52, name: "Jayden Zamora", pos: "OL" },
  { n: 53, name: "Jaron Brickley", pos: "DL" },
  { n: 54, name: "Blake Christner", pos: "DL" },
  { n: 55, name: "Ben Selzer", pos: "OL" },
  { n: 56, name: "Grant Harkless", pos: "OL" },
  { n: 58, name: "Braxton Arriaga", pos: "OL" },
  { n: 59, name: "Cruz Vergara", pos: "DL" },
  { n: 60, name: "Austin Mowery", pos: "OL" },
  { n: 61, name: "Brody Lose", pos: "DL" },
  { n: 62, name: "Xavier Bodle", pos: "DL" },
  { n: 65, name: "Kyle Shaffer", pos: "OL" },
  { n: 66, name: "Jaxson Harkless", pos: "DL" },
  { n: 67, name: "Frank Morgan", pos: "OL" },
  { n: 68, name: "Oliver Barker", pos: "OL" },
  { n: 69, name: "Jason Lykins", pos: "DL" },
  { n: 70, name: "Laila Simmons", pos: "DL" },
  { n: 71, name: "Jamison Schemann", pos: "OL" },
  { n: 73, name: "Caleb Brown", pos: "OL" },
  { n: 74, name: "Ethan Butler", pos: "OL" },
  { n: 75, name: "Jonathan Borne", pos: "OL" },
  { n: 77, name: "Owen Gunsett", pos: "OL" },
  { n: 78, name: "Jason Moore", pos: "DL" },
  { n: 81, name: "Camron Barger", pos: "WR" },
  { n: 82, name: "Jett Beaulieu", pos: "CB" },
  { n: 83, name: "Wyatt Betz", pos: "WR" },
  { n: 84, name: "Daniel Selking", pos: "WR" },
  { n: 85, name: "Keegan Long", pos: "OL" },
  { n: 88, name: "Grayson Riehm", pos: "K" },
];

/** Built-in rosters offered by the in-game "Import roster" picker. */
export const BUILTIN_ROSTERS: { key: string; label: string; roster: { n: number; name: string; pos: string }[] }[] = [
  { key: "bellmont", label: "Bellmont Braves", roster: BELLMONT_ROSTER },
  { key: "northridge", label: "Northridge Raiders", roster: NORTHRIDGE_ROSTER },
  { key: "columbia-city", label: "Columbia City Eagles", roster: COLUMBIA_CITY_ROSTER },
];
